<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KrematoriumSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Data Kompor
        DB::table('kompor_krematoriums')->insert([
            ['jumlah' => 5, 'kondisi' => 'Bisa Digunakan', 'keterangan' => 'Bisa Diperbaiki'],
            ['jumlah' => 5, 'kondisi' => 'Rusak', 'keterangan' => 'Tidak Berfungsi'],
        ]);

        // 2. Data Catatan Jabatan
        DB::table('catatan_jabatan_krematoriums')->insert([
            ['jabatan' => 'Jabatan 3 (Orang Hari)', 'jumlah_orang' => 28, 'keterangan' => 'Satgas'],
            ['jabatan' => 'Jabatan', 'jumlah_orang' => 170, 'keterangan' => 'Pengelola Pelayanan Umum'],
            ['jabatan' => 'Jabatan', 'jumlah_orang' => 3, 'keterangan' => 'Penata Layanan Operasional'],
        ]);

        // 3. Data Pegawai (Lengkap sesuai SQL)
        $pegawai = [
            ['no' => 1, 'nama_pegawai' => 'YULIANTO WIBOWO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578102207890003', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kapas Krampung'],
            ['no' => 2, 'nama_pegawai' => 'MUSTOFA', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3519132501880002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kapas Krampung'],
            ['no' => 3, 'nama_pegawai' => 'DAURI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578100311780007', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kapas Krampung'],
            ['no' => 4, 'nama_pegawai' => 'EKO DARMAWAN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515111110830003', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kapas Krampung'],
            ['no' => 5, 'nama_pegawai' => 'WAHYU WIDODO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3519130709890001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kapas Krampung'],
            ['no' => 6, 'nama_pegawai' => 'DIDIK EFENDI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578103110800002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kapas Krampung'],
            ['no' => 7, 'nama_pegawai' => 'SLAMET HARTONO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578101802860004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kapas Krampung'],
            ['no' => 8, 'nama_pegawai' => 'WAHYU HARIANTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515110101830044', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kapas Krampung'],
            ['no' => 11, 'nama_pegawai' => 'WAHYU SUPRAYITNO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578161409930003', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kapas Krampung'],
            ['no' => 12, 'nama_pegawai' => 'RANGGA BAGUS SYAHPUTRA', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578160309030002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kapas Krampung'],
            ['no' => 13, 'nama_pegawai' => 'NYOTO HARIYANTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3519100207860001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kapas Krampung'],
            ['no' => 14, 'nama_pegawai' => 'IHSANUL AMAL', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578263001900001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kapas Krampung'],
            ['no' => 16, 'nama_pegawai' => 'ERIK DEFIONO, S HUM', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578213012820001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Wonokusumo'],
            ['no' => 20, 'nama_pegawai' => 'ERVIN DWI HANDOKO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578162709890005', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Wonokusumo'],
            ['no' => 21, 'nama_pegawai' => 'FEBRI DJUNAEDI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578160602880004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Wonokusumo'],
            ['no' => 22, 'nama_pegawai' => 'JOKO WARDOYO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578292911770002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Wonokusumo'],
            ['no' => 24, 'nama_pegawai' => 'RYAN SETIAWAN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578030602960001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Karang Tembok'],
            ['no' => 26, 'nama_pegawai' => 'ADI SUJATMIKO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578062301780007', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Karang Tembok'],
            ['no' => 27, 'nama_pegawai' => 'NOVITRI BUDIANTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578061711800003', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Karang Tembok'],
            ['no' => 28, 'nama_pegawai' => 'SUPRIADI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578160807710003', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Karang Tembok'],
            ['no' => 29, 'nama_pegawai' => 'ANDIK SANTOSO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3517111902820006', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Karang Tembok'],
            ['no' => 30, 'nama_pegawai' => 'ZAINAL ARIFIN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578261308750003', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Karang Tembok'],
            ['no' => 31, 'nama_pegawai' => 'ALVIN TOYYIBIN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578111310990002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Karang Tembok'],
            ['no' => 32, 'nama_pegawai' => 'ARYE MUSTOFA', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578172310920001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Karang Tembok'],
            ['no' => 33, 'nama_pegawai' => 'RACHMAD FIRMANSYAH', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3503010207040004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Karang Tembok'],
            ['no' => 35, 'nama_pegawai' => 'SUDARMONO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3522082510870004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Asem Jajar'],
            ['no' => 36, 'nama_pegawai' => 'MOCHAMAD IRFANTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515112011850002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Asem Jajar'],
            ['no' => 37, 'nama_pegawai' => 'WAWAN HARIYANTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3524162911800001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Asem Jajar'],
            ['no' => 38, 'nama_pegawai' => 'AKHMAD SUFANDI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515113005860001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Asem Jajar'],
            ['no' => 39, 'nama_pegawai' => 'TRI SULISTIONO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3506170000000000', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Asem Jajar'],
            ['no' => 40, 'nama_pegawai' => 'NIRWANSYAH ROZI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578060309800002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Asem Jajar'],
            ['no' => 41, 'nama_pegawai' => 'PUJI PURNOMO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578061404700006', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Asem Jajar'],
            ['no' => 42, 'nama_pegawai' => 'FITHROTUN NADHIROH', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3524236008820002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kalianak'],
            ['no' => 43, 'nama_pegawai' => 'SAIFUL AMIN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515020101870013', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kalianak'],
            ['no' => 44, 'nama_pegawai' => 'ACH DANANG BUDI UTOMO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515112703910001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kalianak'],
            ['no' => 45, 'nama_pegawai' => 'SUHARTONO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578102404860001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kalianak'],
            ['no' => 46, 'nama_pegawai' => 'MAMAT SAPI\'I', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3525130607870014', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kalianak'],
            ['no' => 47, 'nama_pegawai' => 'AKHMAD KHUSNUL MUKHTAR', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515111912870001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kalianak'],
            ['no' => 48, 'nama_pegawai' => 'NUR CAHYO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578091504970002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kalianak'],
            ['no' => 49, 'nama_pegawai' => 'MASHURI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515110802690001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kalianak'],
            ['no' => 50, 'nama_pegawai' => 'CAMRON MARULAK TUA', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578062404810002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kalianak'],
            ['no' => 51, 'nama_pegawai' => 'MUCHAMMAD HASYIMI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578250807910001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kalianak'],
            ['no' => 52, 'nama_pegawai' => 'MOH. ZAINUDDIN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3524212506900001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kalianak'],
            ['no' => 53, 'nama_pegawai' => 'FARID SANTOSO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578291411790002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kalianak'],
            ['no' => 54, 'nama_pegawai' => 'MOCH EKA FIRMANSYAH', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578062806970008', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kalianak'],
            ['no' => 55, 'nama_pegawai' => 'PARMIN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3519103007780002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kalianak'],
            ['no' => 56, 'nama_pegawai' => 'ALDINA MITA KURNIAWATI', 'jenis_kelamin' => 'Perempuan', 'nik' => '3505196801970004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Putat Gede'],
            ['no' => 57, 'nama_pegawai' => 'MOH. ALI DAVA FIRNANDA PUTRA', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3524160907990001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Putat Gede'],
            ['no' => 58, 'nama_pegawai' => 'ABDUL GHAFUR', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578061511830004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Putat Gede'],
            ['no' => 59, 'nama_pegawai' => 'AGUS EFENDI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578061004800004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Putat Gede'],
            ['no' => 61, 'nama_pegawai' => 'JURI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3522161105700004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Putat Gede'],
            ['no' => 63, 'nama_pegawai' => 'ALI SHODIQIN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3522241901940002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Putat Gede'],
            ['no' => 64, 'nama_pegawai' => 'SUTANTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578061604750006', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Putat Gede'],
            ['no' => 65, 'nama_pegawai' => 'BUDIANTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3506171008860007', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Putat Gede'],
            ['no' => 66, 'nama_pegawai' => 'MOHAMAD FAUDJI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515132205820004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Putat Gede'],
            ['no' => 67, 'nama_pegawai' => 'MUSLIK', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578061112860002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Putat Gede'],
            ['no' => 68, 'nama_pegawai' => 'MOHAMMAD JEFRI SUSAMTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578180202930001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Putat Gede'],
            ['no' => 69, 'nama_pegawai' => 'FAJAR RAMADHAN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578191601970002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Putat Gede'],
            ['no' => 70, 'nama_pegawai' => 'SUNARDI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3517082008720006', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Putat Gede'],
            ['no' => 71, 'nama_pegawai' => 'MOHAMMAD HANAFI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578302412880001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Putat Gede'],
            ['no' => 72, 'nama_pegawai' => 'MOCHAMMAD AZIZ', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515112009860001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Simo Kwagean'],
            ['no' => 73, 'nama_pegawai' => 'RIANTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578062609820007', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Simo Kwagean'],
            ['no' => 74, 'nama_pegawai' => 'MOCH. KHOIRUL', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578221601810001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Simo Kwagean'],
            ['no' => 75, 'nama_pegawai' => 'BAGUS RAHMAD', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3517061511880002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Simo Kwagean'],
            ['no' => 76, 'nama_pegawai' => 'GUNAWAN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578092401850001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Simo Kwagean'],
            ['no' => 77, 'nama_pegawai' => 'FEBBY SARTIKA', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578094803950002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kembang Kuning'],
            ['no' => 78, 'nama_pegawai' => 'FITRIONO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515141704910005', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kembang Kuning'],
            ['no' => 79, 'nama_pegawai' => 'MOCH RIFAI, S.IP', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3504012510700001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kembang Kuning'],
            ['no' => 80, 'nama_pegawai' => 'DIMAS AJI PAMUNGKAS', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578060210920006', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kembang Kuning'],
            ['no' => 81, 'nama_pegawai' => 'T A U H I D', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3525081207860001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kembang Kuning'],
            ['no' => 82, 'nama_pegawai' => 'RENO WILBANTARA', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578060606860006', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kembang Kuning'],
            ['no' => 84, 'nama_pegawai' => 'ANDI PRAWOTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578061102770004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kembang Kuning'],
            ['no' => 85, 'nama_pegawai' => 'SUTRISNO JOKO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3506112906840001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kembang Kuning'],
            ['no' => 86, 'nama_pegawai' => 'BUDIONO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3506100401680004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kembang Kuning'],
            ['no' => 87, 'nama_pegawai' => 'FATKHUR ROHMAN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3525081205810002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kembang Kuning'],
            ['no' => 88, 'nama_pegawai' => 'IMAM SYAFII', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578091008770002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kembang Kuning'],
            ['no' => 90, 'nama_pegawai' => 'MEDI SANTOSO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578103006840016', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kembang Kuning'],
            ['no' => 91, 'nama_pegawai' => 'SUGIANTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515122606750001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kembang Kuning'],
            ['no' => 92, 'nama_pegawai' => 'HABIB ABDULLAH', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578060000000000', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kembang Kuning'],
            ['no' => 93, 'nama_pegawai' => 'SUWADI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3525040507730003', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kembang Kuning'],
            ['no' => 94, 'nama_pegawai' => 'SOLICHIN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578071103750005', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kembang Kuning'],
            ['no' => 95, 'nama_pegawai' => 'ADITYA WAHYUDI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578290602940002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Peneleh'],
            ['no' => 98, 'nama_pegawai' => 'ARI MARIONO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578252809760001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Peneleh'],
            ['no' => 99, 'nama_pegawai' => 'NUR CHOLIS', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578010304820001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Peneleh'],
            ['no' => 101, 'nama_pegawai' => 'ERNA KUSUMAWATI,SE', 'jenis_kelamin' => 'Perempuan', 'nik' => '3578104605720002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Peneleh'],
            ['no' => 102, 'nama_pegawai' => 'ZULVAN ARDIAN PRASETYO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578060703900002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Peneleh'],
            ['no' => 103, 'nama_pegawai' => 'ABDUL ROHMAN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3517112901800001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 104, 'nama_pegawai' => 'IMAM SOEGIARTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578302607820001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 105, 'nama_pegawai' => 'MOHAMAD WAHYUDI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3525042905850002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 106, 'nama_pegawai' => 'RUMLAN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3522011201720001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 107, 'nama_pegawai' => 'SONNY DWI PURNOMO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3306141106910002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 108, 'nama_pegawai' => 'SUMARNO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578271104730004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 109, 'nama_pegawai' => 'SUPRAMINTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3524211211880001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 110, 'nama_pegawai' => 'FANDY SATYA WIBOWO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578040507860002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 111, 'nama_pegawai' => 'HUSIN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3514011703850003', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 112, 'nama_pegawai' => 'M. ZAELANI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578301901980001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 113, 'nama_pegawai' => 'MICHEL ANTONIOS YOHANES T', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515120908870001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 114, 'nama_pegawai' => 'MOCHAMMAD ARIF YULIANTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515130207810007', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 115, 'nama_pegawai' => 'SOLEH', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3522010508690001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 116, 'nama_pegawai' => 'YULIANTO ADI WASKITO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578160000000000', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 117, 'nama_pegawai' => 'EDY SUSANTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578143011890002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 119, 'nama_pegawai' => 'NUR SALIM', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578062004860005', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 121, 'nama_pegawai' => 'SUYITNO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578183108820001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 122, 'nama_pegawai' => 'NUR KHOTIB', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578181805820004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 123, 'nama_pegawai' => 'SADIMUN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578061011780011', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 124, 'nama_pegawai' => 'TRI LAKSANA YUDHA', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578142103810004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Babat Jerawat'],
            ['no' => 125, 'nama_pegawai' => 'ATIK PUSPASARI', 'jenis_kelamin' => 'Perempuan', 'nik' => '3524196303870001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Ngagel'],
            ['no' => 126, 'nama_pegawai' => 'AGUS RAHMAD', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3516170000000000', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Ngagel'],
            ['no' => 127, 'nama_pegawai' => 'AHMAD ASY\'ARI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578091308740001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Ngagel'],
            ['no' => 128, 'nama_pegawai' => 'HELPI SUSILO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578130809720001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Ngagel'],
            ['no' => 129, 'nama_pegawai' => 'MOH. FAUZI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515140702820001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Ngagel'],
            ['no' => 131, 'nama_pegawai' => 'SANDI SAPUTRA', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515102611820002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Ngagel'],
            ['no' => 132, 'nama_pegawai' => 'MOCHAMAD MOCHTADDIN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578092306880002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Ngagel'],
            ['no' => 133, 'nama_pegawai' => 'ACHMAD GINANJAR', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578090105940003', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Ngagel'],
            ['no' => 135, 'nama_pegawai' => 'ACHMAD LUTHFI SYAUKANI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578101008900006', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Ngagel'],
            ['no' => 136, 'nama_pegawai' => 'AGUS RACHMAD', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578130510700001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 137, 'nama_pegawai' => 'AGUS SULISTIONO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578092108790003', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 138, 'nama_pegawai' => 'ALI SYAMSUDIN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578090701820003', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 139, 'nama_pegawai' => 'HIDAYATUL ROHMAN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3525150506910005', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 140, 'nama_pegawai' => 'ASHAD', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578081511720004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 141, 'nama_pegawai' => 'HERU SISWANTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578102606860008', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 142, 'nama_pegawai' => 'KACUNG SISWANTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578062603840011', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 143, 'nama_pegawai' => 'MAT SAPUAN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578090908720001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 144, 'nama_pegawai' => 'MOCH CHUSAINI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578090506790001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 145, 'nama_pegawai' => 'MOCH. SYAIFUL', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578090211790001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 146, 'nama_pegawai' => 'MOHAMMAD SHOLEH', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578090104850005', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 147, 'nama_pegawai' => 'MUHAMMAD SAFAK', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578090204720008', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 148, 'nama_pegawai' => 'NANIK SUPATMI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3502074601940002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 149, 'nama_pegawai' => 'SUMANTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3506100602830002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 150, 'nama_pegawai' => 'ABU ASAN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515110208720001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 151, 'nama_pegawai' => 'AINUL YAQIN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578241407900002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 152, 'nama_pegawai' => 'ARIANTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515111501920001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 154, 'nama_pegawai' => 'IRFAN HERMANTO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578041702900006', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 155, 'nama_pegawai' => 'MOCH. RIDUWAN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578192911760002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 156, 'nama_pegawai' => 'MUH. SAIFUL AFITRI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3502071002970001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 157, 'nama_pegawai' => 'RAHMAT HIDAYATULLOH', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578160812850002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 158, 'nama_pegawai' => 'RIZAL IBNU AZIS', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578251105940003', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 159, 'nama_pegawai' => 'RIZKY PUTRA PRAWIRA', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578061305880001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 160, 'nama_pegawai' => 'SISWANDI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3522081110870004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 161, 'nama_pegawai' => 'SLAMET MARIYONO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578131309790001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 162, 'nama_pegawai' => 'YANUAR FEBRI SANTOSA', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3404072801910003', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 163, 'nama_pegawai' => 'YUSUF BOBY AIRLANGGA', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515111609870006', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 164, 'nama_pegawai' => 'FANDITIA RACHMAN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578091205850001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 165, 'nama_pegawai' => 'SOLIKIN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3522011712850006', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 167, 'nama_pegawai' => 'PARTONO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578012001820003', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 168, 'nama_pegawai' => 'LUKMAN HADI WIJAYA', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578182511810002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 169, 'nama_pegawai' => 'UMAN SLAMET', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578192209830004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 173, 'nama_pegawai' => 'YULIATI', 'jenis_kelamin' => 'Perempuan', 'nik' => '3578105007800003', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 174, 'nama_pegawai' => 'MARISAL AGUS SETIYAWAN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578100508900004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tpu Keputih'],
            ['no' => 175, 'nama_pegawai' => 'RAHMAD HIDAYAT', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515181005930004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Krematorium'],
            ['no' => 176, 'nama_pegawai' => 'DARKO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578091902800005', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Krematorium'],
            ['no' => 177, 'nama_pegawai' => 'DWI ANGGO WIBOWO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3502072512790002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Krematorium'],
            ['no' => 179, 'nama_pegawai' => 'MOCHAMAD SISWOYO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578061212970001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Krematorium'],
            ['no' => 181, 'nama_pegawai' => 'SUMITRO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3502072310780003', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Krematorium'],
            ['no' => 182, 'nama_pegawai' => 'EKA YULI WAHYUDI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578101510020001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Krematorium'],
            ['no' => 183, 'nama_pegawai' => 'AJIS', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515112303770001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Krematorium'],
            ['no' => 184, 'nama_pegawai' => 'ARMAN TAUFIK', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578271801880001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tembok Gede'],
            ['no' => 185, 'nama_pegawai' => 'ASHARI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578242003790004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tembok Gede'],
            ['no' => 186, 'nama_pegawai' => 'SAMSUL ANAM', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578072004830001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tembok Gede'],
            ['no' => 187, 'nama_pegawai' => 'CHOLIK', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578160000000000', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tembok Gede'],
            ['no' => 188, 'nama_pegawai' => 'FANDI ACHMAD', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578112809880001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tembok Gede'],
            ['no' => 189, 'nama_pegawai' => 'M. DIMAS PRASETYO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515110405910004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tembok Gede'],
            ['no' => 190, 'nama_pegawai' => 'MUHAMMAD ALFIAN MISBACH', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578061812880004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tembok Gede'],
            ['no' => 191, 'nama_pegawai' => 'SHOLICHIN', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578161305800003', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tembok Gede'],
            ['no' => 192, 'nama_pegawai' => 'YA\'QUP', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3516162911760004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tembok Gede'],
            ['no' => 193, 'nama_pegawai' => 'DADANG RAHMAT AGUNG', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578292810950002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tembok Gede'],
            ['no' => 194, 'nama_pegawai' => 'MOCHAMMAD KAMIL', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578171008910001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tembok Gede'],
            ['no' => 196, 'nama_pegawai' => 'NURMAN HIDAYAT', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578302905740001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Tembok Gede'],
            ['no' => 197, 'nama_pegawai' => 'HARIS ANGGORO NASUTION', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578140205960002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'UPTSA'],
            ['no' => 198, 'nama_pegawai' => 'MUHAMMAD SIROJ ALMUSTAFID', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515101510970002', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kantor DLH'],
            ['no' => 199, 'nama_pegawai' => 'MOHAMMAD ADI SUMARYONO', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578281202920001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kantor DLH'],
            ['no' => 200, 'nama_pegawai' => 'M. KUSYAIRI', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3515070702930004', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kantor DLH'],
            ['no' => 201, 'nama_pegawai' => 'DWIJA WIRANANDHA, ST', 'jenis_kelamin' => 'Laki-laki', 'nik' => '3578051711840001', 'status' => 'PPPK Paruh Waktu', 'lokasi_kerja' => 'Kantor DLH'],
        ];
        DB::table('pegawai_krematoriums')->insert($pegawai);
    }
}